In [1]:
import pandas as pd
import numpy as np

In [2]:
s= pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [3]:
# s = pd.Series([11,33,22,44])
# s

In [4]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [5]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [6]:
pd.Series(range(10,14))

0    10
1    11
2    12
3    13
dtype: int64

In [7]:
s.name = '인구'
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [8]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

In [11]:
#시리즈 인덱싱
#인덱스 라벨을 이용한 인덱싱 배열 인덱싱으로 인덱스 라벨을 이용한 슬라이싱도 가능

In [18]:
# 시리즈 데이터를 인덱싱하면 값이 나옴
s[2], s['부산']

C:\Users\user\AppData\Local\Temp\ipykernel_10020\1704493990.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[2], s['부산']


(2890451, 3448737)

In [20]:
# 자료 순서 바꾸기
s[[0,3,1]]

C:\Users\user\AppData\Local\Temp\ipykernel_10020\1622615176.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[0,3,1]]


도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [23]:
s[["서울","대구","부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [25]:
s[(250e4 < s) & (s < 500e4)] #인구가 250만 초과, 500 초과, 500만 미만인 경우

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [27]:
s[1:2] # 두번쨰 (1)부터 새번째 (2) 까지 네번째 3() 미포함

도시
부산    3448737
Name: 인구, dtype: int64

In [29]:
s['부산':'인천'] # 부산에서 대구까지( 대구 포함)

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [31]:
#라벨값이 영문 문자열이 경우

In [33]:
s0 = pd.Series(range(3), index=['a','b','c'])
s0

a    0
b    1
c    2
dtype: int64

In [35]:
s0.values

array([0, 1, 2], dtype=int64)

In [37]:
s0.tolist()

[0, 1, 2]

In [39]:
s0.a

0

In [41]:
s0.c

2

In [43]:
# 시리즈와 딕셔너리 자료형
# 시리즈 객체는 라벨 값에 의해

In [45]:
'서울' in s # 인덱스 라벨 중 서울이 있는가

True

In [47]:
'대전' in s # 인덱스 라벨 중 서울이 있는가

False

In [49]:
for k, v in s.items():
    print('%s = %d' %(k,v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [51]:
s2 = pd.Series({"서울": 9631482, "부산":3393191, "인천":2632035, 
                "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [53]:
s2 = pd.Series({"서울": 9631482, "부산":3393191, "인천":2632035, 
                "대전": 1490158},
                index=['부산','서울','인천','대전'])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [55]:
# 딕셔너리는 순서 보장 x
s2[1]

C:\Users\user\AppData\Local\Temp\ipykernel_10020\3952165525.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[1]


9631482

In [57]:
# 인덱스 기반 연산
# 2015년과 2010의 인구 증가 계산

In [59]:
# 인덱스가 같은 데이터에 대해서만 계산 가능
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [61]:
#null 값이 아닌것 찾기
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [63]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [65]:
# 증가율 계산
rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

In [67]:
#1-6. 데이터 갱신, 추가, 삭제
#인덱싱을 이용하면 딕셔너리 처럼 데이트를 갱신(update) 하거나 추가(add) 가능 

In [69]:
rs['부산'] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [71]:
# 데이터 삭제
del rs['부산']
rs

서울    2.832690
인천    9.818107
dtype: float64

In [73]:
#1 연습문제
#1 임의로 두개의 시리즈 객체를 만든다 모두 문자열 인덱스를 가져야 하며 두 시리즈에 공통적으로 포함되지 않는 라벨이 있어야 한다
#2 위에서 만든 두 시리즈 객체를 이용하여 사칙 연산을 한다

In [75]:
ss = pd.Series([1357,2468,0000,9999], index = ['a','b','c','d'])
ss2 = pd.Series([2222,4444,3333,1234], index = ['c','d','e','f'])
ss, ss2
ss.a + ss2.d, ss.b - ss2.e, ss.c*ss2.f, ss.d/ss2.c

(5801, -865, 0, 4.5)

In [77]:
# 데이터프레임
# 2차원 리스트를 매개변수로 전달하는 구조
# 2차원이므로 행방향 인덱스와 열방향 인덱스가 존재
# 데이터프레임은 열까지 추가되어 열, 인덱스, 값으로 구성
# 시리즈는 인덱스와 값으로 구성

In [79]:
values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one','two','thress']
columns = ['a','b','c']

df = pd.DataFrame(values, index=index, columns=columns)

print('데이터프레임 출력:')
print('-'*18)
print(df)

데이터프레임 출력:
------------------
        a  b  c
one     1  2  3
two     4  5  6
thress  7  8  9


In [81]:
df1 =pd.DataFrame(values, columns = columns)
print(df1)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9


In [83]:
print(df.index)
print(df.columns)
print(df.values)

Index(['one', 'two', 'thress'], dtype='object')
Index(['a', 'b', 'c'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]

df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [87]:
type(df)

pandas.core.frame.DataFrame

In [88]:
df = pd.DataFrame(data, columns = ['학번','이름','점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [90]:
# 딕셔너리로 생성하기
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [93]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [95]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [97]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [99]:
# 전치 가능
df.T

서울       부산       인천       대구
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [101]:
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [103]:
# "2010-2015 증가율"이라는 이름의 열 추가
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [105]:
# "2005-2010 증가율"이라는 이름의 열 추가
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(3)
df

지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83         -1.343
부산  경상권  3448737  3393191  3512547  3655437           1.63         -3.398
인천  수도권  2890451  2632035  2517680  2466338           9.82          4.542
대구  경상권  2466052  2431774  2456016  2473990           1.41         -0.987

In [107]:
# "2010-2015 증가율"이라는 이름의 열 삭제
del df["2010-2015 증가율"]
df

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         -1.343
부산  경상권  3448737  3393191  3512547  3655437         -3.398
인천  수도권  2890451  2632035  2517680  2466338          4.542
대구  경상권  2466052  2431774  2456016  2473990         -0.987

In [109]:
#3-3 열 인덱싱
#데이터프레임은 열 라벨을 키로, 열 시리즈를 값으로 가지는 딕셔너리와 비슷함
#데이터프레임을 인덱싱을 할 때도 열 라벨(column label)을 키값으로 생각하여 인덱싱 가능

In [111]:
# 하나의 열만 인덱싱하면 시리즈가 반환된다.
df["지역"]

서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [113]:
# 여러개의 열을 인덱싱하면 부분적인 데이터프레임이 반환된다.
df[["2010", "2015"]]

2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [115]:
# 2010이라는 열을 반환하면서 데이터프레임 자료형을 유지
df[["2010"]]

2010
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [117]:
type(df[["2010"]])

pandas.core.frame.DataFrame

In [119]:
# 2010이라는 열을 반환하면서 시리즈 자료형으로 변환
df["2010"]

서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [121]:
type(df["2010"])

pandas.core.series.Series

In [123]:
df

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         -1.343
부산  경상권  3448737  3393191  3512547  3655437         -3.398
인천  수도권  2890451  2632035  2517680  2466338          4.542
대구  경상권  2466052  2431774  2456016  2473990         -0.987

In [177]:
# 문자열 라벨을 가지는 경우 정수 인덱스를 열 인덱싱에 사용할 수 없음
df[0]

KeyError: 0

In [125]:
# 열 인덱스가 정수형일땐 인덱스 값에 정수 사용 가능
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [127]:
(0,12,1)

(0, 12, 1)

In [129]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int32

In [131]:
df2[[1, 2]]

1   2
0  1   2
1  5   6
2  9  10

In [133]:
#행 인덱싱
# 슬라이싱 사용
# 인덱스가 문자 라벨이면 라벨 슬라이싱 가능

In [135]:
df

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         -1.343
부산  경상권  3448737  3393191  3512547  3655437         -3.398
인천  수도권  2890451  2632035  2517680  2466338          4.542
대구  경상권  2466052  2431774  2456016  2473990         -0.987

In [137]:
df[:1]

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         -1.343

In [139]:
df[1:2]

지역     2015     2010     2005     2000  2005-2010 증가율
부산  경상권  3448737  3393191  3512547  3655437         -3.398

In [141]:
df[1:3]

지역     2015     2010     2005     2000  2005-2010 증가율
부산  경상권  3448737  3393191  3512547  3655437         -3.398
인천  수도권  2890451  2632035  2517680  2466338          4.542

In [143]:
df["서울":"부산"]

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         -1.343
부산  경상권  3448737  3393191  3512547  3655437         -3.398

In [145]:
df

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         -1.343
부산  경상권  3448737  3393191  3512547  3655437         -3.398
인천  수도권  2890451  2632035  2517680  2466338          4.542
대구  경상권  2466052  2431774  2456016  2473990         -0.987

In [147]:
# 개별 데이터 인덱싱 / 열 라벨로 인덱싱 후 행 라벨로 인덱싱하면 원하는 개별 데이터 추출
df['2010']['대구']

2431774

In [149]:
#연습문제2
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [151]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [153]:
#1. 수학점수 시리즈로
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [155]:
#2 국,영 df
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [157]:
#3 평균열 추가
# df['평균'] = (df['국어'] + df['수학'] + df['영어']) / 3
# df
df['평균'] = round(df.mean(axis = 1),2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [159]:
#4 방자 영어 80으로 수정 평균도
# del df['영어']['방자']
# del df['평균']['방자']
# df['영어']['방자'] = 80
# df['평균']['방자'] = (df['국어']['방자'] + df['수학']['방자'] + df['영어']['방자']) / 3
# df
df.loc['방자','영어'] = 80
df['평균'] = round(df.mean(axis = 1),2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  56.67

In [161]:
#5 춘향 점수 df
df[:1]
# type(df[:1]])

국어  영어  수학     평균
춘향  80  90  90  86.67

In [163]:
#6 향단 점수 시리즈
# df1 = df.T
# df1['향단']

# df.loc['향단']

pd.Series(list(df[2:3].values),index=['향단'])

향단    [70.0, 60.0, 80.0, 70.0]
dtype: object

In [ ]:
#df 조회

In [171]:
# 앞 부분을 3개만 보기
print(df.head(3))

    국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00


In [173]:
# 뒷 부분을 3개만 보기
print(df.tail(3))

    국어  영어  수학     평균
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  56.67


In [175]:
# '학번'에 해당되는 열을 보기
df['국어']

춘향    80
몽룡    90
향단    70
방자    30
Name: 국어, dtype: int64

In [ ]:
# 외부 데이터 읽기

In [183]:
df = pd.read_csv('RegularSeasonCompactResults.csv')
print(df)
# df.head()

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0         1985      20     1228      81     1328      64    N      0
1         1985      25     1106      77     1354      70    H      0
2         1985      25     1112      63     1223      56    H      0
3         1985      25     1165      70     1432      54    H      0
4         1985      25     1192      86     1447      74    H      0
...        ...     ...      ...     ...      ...     ...  ...    ...
156084    2018     132     1153      56     1222      55    N      0
156085    2018     132     1172      58     1348      57    N      0
156086    2018     132     1209      74     1426      61    N      0
156087    2018     132     1246      77     1397      72    N      0
156088    2018     132     1335      68     1217      65    N      0

[156089 rows x 8 columns]


In [185]:
# 인덱스 자동 부여
df.index

RangeIndex(start=0, stop=156089, step=1)

In [ ]:
#csv파일 입력 및 %%writefile 명령


In [191]:
%%writefile sample1.csv
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample1.csv


In [193]:
pd.read_csv('sample1.csv')

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [195]:
%%writefile sample2.csv
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample2.csv


In [197]:
pd.read_csv('sample2.csv', names=['c1', 'c2', 'c3'])

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [199]:
pd.read_csv('sample1.csv', index_col='c1')

c2      c3
c1              
1   1.11     one
2   2.22     two
3   3.33   three

In [201]:
%%writefile sample4.txt
파일 제목: sample4.txt
데이터 포맷의 설명:
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample4.txt


In [203]:
pd.read_csv('sample4.txt', skiprows=[0, 1, 4])

c1    c2      c3
0   1  1.11     one
1   3  3.33   three

In [205]:
%%writefile sample5.csv
c1, c2, c3
1, 1.11, one
2, , two
누락, 3.33, three

Writing sample5.csv


In [207]:
df = pd.read_csv('sample5.csv', na_values=['누락'])
df

c1     c2      c3
0  1.0   1.11     one
1  2.0            two
2  NaN   3.33   three

In [ ]:
df = pd.read_csv('sample5.csv', na_values=['누락', ' '])
df

In [ ]:
#df 출력


In [211]:
df.to_csv('sample6.csv')

In [213]:
# !type 함수를 사용해서 파일의 내용을 확인할 수 있음/ 정확한 저장 확인
!type sample6.csv

,c1, c2, c3
0,1.0, 1.11, one
1,2.0, , two
2,, 3.33, three


In [215]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                  index=["a", "b", "c"],
                  columns=["A", "B", "C", "D"])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [217]:
# loc 인덱서를 사용하면서 인덱스를 하나만 넣으면 행(row)을 선택
df.loc["a"]

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [219]:
# 슬라이스도 가능
df.loc["b":"c"]

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [221]:
# 이 때에는 loc를 쓰지 않는 경우와 같음
df["b":"c"]

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [229]:
print(df)
df.A > 15

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21


a    False
b    False
c     True
Name: A, dtype: bool

In [225]:
df.loc[df.A > 15]

A   B   C   D
c  18  19  20  21

In [233]:
df2 = pd.DataFrame(np.arange(10,26).reshape(4,4), columns=['A','B','c','D'])
df2

A   B   c   D
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [237]:
# 슬라이스의 마지막 값 포함 loc는 문자기반
df2.loc[1:2]

A   B   c   D
1  14  15  16  17
2  18  19  20  21

In [ ]:
#행렬 인덱싱

In [239]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                  index=["a", "b", "c"],
                  columns=["A", "B", "C", "D"])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [247]:
df.loc['a','A']

10

In [251]:
df.loc['b':,'A']

b    14
c    18
Name: A, dtype: int32

In [253]:
df.loc["a", :]

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [255]:
df.loc[["a", "b"], ["B", "D"]]

B   D
a  11  13
b  15  17

In [257]:
# A열에서 10보다 큰 행을 먼저 선택
df.loc[df.A > 10]

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [259]:
df.loc[df.A > 10, ["C", "D"]]

C   D
b  16  17
c  20  21

In [ ]:
# iloc

In [261]:
df = pd.DataFrame(np.arange(10, 22, 1).reshape(3, 4),
                  index=["a", "b", "c"],
                  columns=["A", "B", "C", "D"])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [263]:
df.iloc[0, 1]

11

In [265]:
df.iloc[:2, 2]

a    12
b    16
Name: C, dtype: int32

In [267]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [269]:
df.iloc[0, -2:]

C    12
D    13
Name: a, dtype: int32

In [271]:
df.iloc[2:3, 1:3]

B   C
c  19  20

In [275]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [277]:
# loc 인덱서와 마찬가지로 인덱스가 하나만 들어가면 행을 선택
df.iloc[-1]

A    18
B    19
C    20
D    21
Name: c, dtype: int32

In [ ]:
#3연습 문제

In [359]:
#1 모든 행과 열에 라벨을 가지는 5X5 데이터프레임을 만든다
df = pd.DataFrame(np.arange(25).reshape(5, 5),index=['ㄱ','ㄴ','ㄷ','ㄹ','ㅁ'], columns=['a','b','c','d','e'])
df

a   b   c   d   e
ㄱ   0   1   2   3   4
ㄴ   5   6   7   8   9
ㄷ  10  11  12  13  14
ㄹ  15  16  17  18  19
ㅁ  20  21  22  23  24

In [369]:
#2 10가지 이상 방법으로 행렬 선택
# df.loc['ㄱ','d']
df.loc[['ㄱ','ㄷ'],['a','c']]
df.iloc[1,2]
df.iloc[4:]

a   b   c   d   e
ㅁ  20  21  22  23  24

In [319]:
s = pd.Series(range(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [321]:
# NaN 값은 세지 않음
s.count()

9

In [323]:
np.random.seed(2)
# np.random.seed(2) 난수를 예측 가능하도록 숫자 바꾸면 다른 배열 생성
df = pd.DataFrame(np.random.randint(5, size=(4, 4)), dtype=float)
#np.random.randint 0에서 5사이의 정수를 가지는 4*4 배열 생성
df.iloc[2, 3] = np.nan
df

0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [325]:
df.count()

0    4
1    4
2    4
3    3
dtype: int64

In [327]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [331]:
#4 문제 타이타닉 승객 데이터 개수 열마다 구해본다
titanic.info

<bound method DataFrame.info of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_m

In [333]:
np.random.seed(1)
s2 = pd.Series(np.random.randint(6, size=100))
s2.tail()

95    4
96    5
97    2
98    4
99    3
dtype: int32

In [335]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

In [337]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

In [339]:
df

0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [341]:
df[3].value_counts()

3
2.0    2
1.0    1
Name: count, dtype: int64

In [343]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

In [345]:
s2.value_counts().sort_index()

0    18
1    22
2    13
3    14
4    17
5    16
Name: count, dtype: int64

In [347]:
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [349]:
# NaN값이 있는 경우에는 정렬하면 NaN값이 가장 나중에 나옴
s.sort_values()

0    0.0
1    1.0
2    2.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
3    NaN
dtype: float64

In [351]:
#큰 수에서 작은 수로 반대 방향 정렬하려면 ascending=False 인수를 지정
s.sort_values(ascending=False)

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
2    2.0
1    1.0
0    0.0
3    NaN
dtype: float64